config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'spaceships#index'

  resources :users do
    get "dashboard", to: "users#mybookings"
    get "dashboard/account_info", to: "users#show"
    get "dashboard/my_spaceships", to: "users#myships"
    get "dashboard/my_spaceships_bookings", to: "users#myshipsbookings"
    get "dashboard/add_review", to: "users#addareview"
    get "bookings/:id/accept", to: "bookings#accept", as: "accept"
    get "bookings/:id/reject", to: "bookings#reject", as: "reject"
    resources :spaceships, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      resources :reviews
      resources :bookings, only: [:index, :new, :edit, :create, :update, :destroy]
    end
    resources :bookings, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :spaceships, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy

  validates :first_name, :last_name, :species, presence: true
  validates :email, uniqueness: true
  validates :species, inclusion: { in: %w(Wookie Human Martian Mandalorian Droid Vulcan Borg Jedi Zetan Calaron) }

  mount_uploader :image, PhotoUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :mybookings, :addareview, :myshipsbookings, :myships]

  def show
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    if @user.save
      redirect_to user_dashboard_account_info_path(@user)
    else
      render :edit
    end
  end

  def mybookings
    authorize @user
    @bookings = Booking.where(user_id: params[:user_id])
  end

  def myships
    authorize @user
    @spaceships = @user.spaceships
  end

  def myshipsbookings
    authorize @user
    @spaceships = @user.spaceships
  end

  def addareview
    authorize @user
    @spaceships = @user.spaceships
    @review_message = params[:message]
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :species, :email, :payment_info, :image)
  end
end

app/views/users/_contactmodal.html.erb
<div class="modal fade" id="contact-modal-<%=booking.user_id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contact Owner</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex align-items-center justify-content-between modal-contact">
        <div>
          <p>Enter your message for</p>
          <p><%= booking.spaceship.user.first_name %> <%= booking.spaceship.user.last_name %></p>
        </div>
        <div>
          <%= cl_image_tag(booking.spaceship.user.image, height: 56, width: 56, crop: :fill, class: "avatar-large") %>
        </div>
      </div>
      <div class="modal-contact">
        <%= simple_form_for([current_user, booking.spaceship, Review.new]) do |f| %>
          <%= f.input :content, label: false %>
          <button type="button" class="btn btn-main" data-dismiss="modal" aria-label="Close">Send Email
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row  justify-content-center">
  <div class="col-12 col-sm-8 col-md-6 space-form">
    <h2>Edit your account:</h2>
    <%= simple_form_for(current_user) do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :species, collection: %w(Wookie Human Martian Mandalorian Droid Vulcan Borg Jedi Zetan Calaron) %>
      <%= f.input :email %>
      <%= f.input :payment_info %>
      <%= f.input :image %>
      <%= f.input :image_cache, as: :hidden %>
      <%= f.button :submit, class: 'btn btn-main' %>
    <% end %>
  </div>
</div>

app/views/users/addareview.html.erb
<div class="dashboard-container" data-index="4">

  <div class="sidebar">
    <%= render 'shared/dashboardsidebar' %>
  </div>

  <div class="dashboard-main">
    <p data-controller= "review" id="review-message">
        <%= @review_message %>
    </p>
    <h2>Drop a Review</h2>
    <% @user.bookings.where(confirmation_status: "done").each do |booking| %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(booking.spaceship.user, booking.spaceship) do %>
          <%= cl_image_tag booking.spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="card-dashboard-body">
          <h3><%= booking.spaceship.name %></h3>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Status: <%= booking.confirmation_status %></p>
          <div class="buttons buttons-right">
            <button type="button" class="btn btn-main buttons buttons-right" data-toggle="modal" data-target="#modal-<%=booking.spaceship.id %>">
              REVIEW
            </button>
          </div>
          <div class="modal fade" id="modal-<%=booking.spaceship.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">DROP A REVIEW</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for([current_user, booking.spaceship, Review.new]) do |f| %>
                    <%= f.input :id, as: :hidden, :input_html => { :value => "#{booking.spaceship_id}" }  %>
                    <%= f.input :rating %>
                    <%= f.input :content %>
                    <%= f.button :submit, class: "btn btn-main" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render "form", current_user: @user %>

app/views/users/mybookings.html.erb
<div class="dashboard-container" data-index="0">

  <div class="sidebar">
    <%= render 'shared/dashboardsidebar' %>
  </div>

  <div class="dashboard-main">

    <h2>Welcome <%= @user.first_name %>, these are your upcoming space trips:</h2>
    <h3>Your current active trip:</h3>
    <% @bookings.where(confirmation_status: 'active').each do |booking| %>
      <% @spaceship = Spaceship.where(id: booking.spaceship_id)[0] %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
          <%= cl_image_tag @spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="tag <%= booking.confirmation_status %>">
          <p><%= booking.confirmation_status %></p>
        </div>
        <div class="card-dashboard-body">
          <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
            <h3><%= @spaceship.name %></h3>
          <% end %>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Status: <%= booking.confirmation_status %></p>
          <div class="buttons buttons-right">
            <%= link_to "CANCEL", user_reject_path(current_user, booking, stay: true), class: "btn btn-main red-btn" %>
            <button type="button" class="btn btn-main btn-modal" data-toggle="modal" data-target="#contact-modal-<%=booking.user_id %>">
              CONTACT OWNER
            </button>
            <%= render 'contactmodal', booking: booking %>
          </div>
        </div>
      </div>
    <% end %>

    <h3>Pending requests:</h3>
    <% @bookings.where(confirmation_status: 'pending').each do |booking| %>
      <% @spaceship = Spaceship.where(id: booking.spaceship_id)[0] %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
          <%= cl_image_tag @spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="tag <%= booking.confirmation_status %>">
          <p><%= booking.confirmation_status %></p>
        </div>
        <div class="card-dashboard-body">
          <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
            <h3><%= @spaceship.name %></h3>
          <% end %>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Status: <%= booking.confirmation_status %></p>
          <div class="buttons buttons-right">
            <%= link_to "CANCEL", user_reject_path(current_user, booking, stay: true), class: "btn btn-main red-btn" %>
            <button type="button" class="btn btn-main btn-modal" data-toggle="modal" data-target="#contact-modal-<%=booking.user_id %>">
              CONTACT OWNER
            </button>
            <%= render 'contactmodal', booking: booking %>
          </div>
        </div>
      </div>
    <% end %>

    <h3>Accepted requests:</h3>
    <% @bookings.where(confirmation_status: 'accepted').each do |booking| %>
      <% @spaceship = Spaceship.where(id: booking.spaceship_id)[0] %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
          <%= cl_image_tag @spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="tag <%= booking.confirmation_status %>">
          <p><%= booking.confirmation_status %></p>
        </div>
        <div class="card-dashboard-body">
          <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
            <h3><%= @spaceship.name %></h3>
          <% end %>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Status: <%= booking.confirmation_status %></p>
          <div class="buttons buttons-right">
            <%= link_to "CANCEL", user_reject_path(current_user, booking, stay: true), class: "btn btn-main red-btn" %>
            <button type="button" class="btn btn-main btn-modal" data-toggle="modal" data-target="#contact-modal-<%=booking.user_id %>">
              CONTACT OWNER
            </button>
            <%= render 'contactmodal', booking: booking %>
          </div>
        </div>
      </div>
    <% end %>

    <h3>Rejected requests:</h3>
    <% @bookings.where(confirmation_status: 'rejected').each do |booking| %>
      <% @spaceship = Spaceship.where(id: booking.spaceship_id)[0] %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
          <%= cl_image_tag @spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="tag <%= booking.confirmation_status %>">
          <p><%= booking.confirmation_status %></p>
        </div>
        <div class="card-dashboard-body">
          <%= link_to user_spaceship_path(@spaceship.user, @spaceship) do %>
            <h3><%= @spaceship.name %></h3>
          <% end %>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Status: <%= booking.confirmation_status %></p>
          <div class="buttons buttons-right">
            <%= link_to "CANCEL", user_reject_path(current_user, booking, stay: true), class: "btn btn-main red-btn" %>
            <button type="button" class="btn btn-main btn-modal" data-toggle="modal" data-target="#contact-modal-<%=booking.user_id %>">
              CONTACT OWNER
            </button>
            <%= render 'contactmodal', booking: booking %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/myships.html.erb
<div class="dashboard-container" data-index="2">

  <div class="sidebar">
    <%= render 'shared/dashboardsidebar' %>
  </div>

  <div class="dashboard-main">
    <h2>My Spaceships:</h2>
    <% @spaceships.each do |spaceship| %>
      <div class="card-dashboard">
        <%= link_to user_spaceship_path(current_user, spaceship) do %>
          <%= cl_image_tag spaceship.image, width: 400, height: 300, crop: :fill %>
        <% end %>
        <div class="card-dashboard-body">
          <%= link_to user_spaceship_path(current_user, spaceship) do %>
            <h3><%= spaceship.name %></h3>
          <% end %>
          <div class="buttons buttons-right">
            <%= link_to "EDIT", edit_user_spaceship_path(current_user, spaceship), class: "btn btn-main" %>
            <%= link_to "DELETE", user_spaceship_path(current_user, spaceship),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "btn btn-main red-btn" %>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to "Add a ship", new_user_spaceship_path(current_user), class: "btn btn-main" %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="dashboard-container" data-index="1">

  <div class="sidebar">
    <%= render 'shared/dashboardsidebar'%>
  </div>

  <div class="dashboard-main">

    <div class="card-account">
      <div class="account-headline row">
        <div class="account-body col-12 col-md-7">
          <h2><%= @user.first_name %>'s Account</h2>
          <div class="account-info">
            <p class="info">First name:</p>
            <p><%= @user.first_name %></p>
          </div>
          <div class="account-info">
            <p class="info">Last name:</p>
            <p><%= @user.last_name %></p>
          </div>
          <div class="account-info">
            <p class="info">Species:</p>
            <p><%= @user.species %></p>
          </div>
          <div class="account-info">
            <p class="info">Email:</p>
            <p><%= @user.email %></p>
          </div>
          <div class="account-info">
            <p class="info">Payment info:</p>
            <p><%= @user.payment_info %></p>
          </div>
    <%= link_to "Edit my profile", edit_user_path(current_user), class: "btn btn-main" %>
        </div>
        <div class="account-pic col-12 col-md-5">
          <%= cl_image_tag(@user.image, height: 200, width: 200, crop: :fill, class: "avatar-account") %>
        </div>
      </div>
    </div>

  </div>

</div>