config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'spaceships#index'

  resources :users do
    get "dashboard", to: "users#mybookings"
    get "dashboard/account_info", to: "users#show"
    get "dashboard/my_spaceships", to: "users#myships"
    get "dashboard/my_spaceships_bookings", to: "users#myshipsbookings"
    get "dashboard/add_review", to: "users#addareview"
    get "bookings/:id/accept", to: "bookings#accept", as: "accept"
    get "bookings/:id/reject", to: "bookings#reject", as: "reject"
    resources :spaceships, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      resources :reviews
      resources :bookings, only: [:index, :new, :edit, :create, :update, :destroy]
    end
    resources :bookings, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_dashboardsidebar.html.erb
<div class="sidebar-body"
      data-controller="tab">

  <ul class="tabs">
    <li id="sidebar-title">Dashboard</li>

    <%= link_to user_dashboard_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">My space trips</li>
    <% end %>

    <%= link_to user_dashboard_account_info_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">Account</li>
    <% end %>

    <%= link_to user_dashboard_my_spaceships_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">My spaceships</li>
    <% end %>

    <%= link_to user_dashboard_my_spaceships_bookings_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">Spaceship bookings</li>
    <% end %>

    <%= link_to user_dashboard_add_review_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">Add a review</li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Website made by Edouard De Prez, François Stevenaert and Federico De Martino
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p><i class="fas fa-rocket"></i> SpaceBNB</p>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", user_dashboard_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to user_dashboard_account_info_path(current_user) do %>
            <%= cl_image_tag(current_user.image, width: 40, height: 40, crop: :fill, :class => "avatar-bordered") %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>